image: smartdevs/magento-php-7.0-cli:latest
pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - composer install
          - php vendor/bin/phpunit -c phpunit.xml --testsuite=unit
          - export ES_HOST=localhost
#          - php vendor/bin/phpunit -c phpunit.xml --testsuite=Integration
        services:
          - elasticsearch
definitions:
  services:
    elasticsearch:
      image: smartdevs/elasticsearch:latest