image: smartdevs/magento-php-7.0-cli:latest
pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - composer install
          - php vendor/bin/phpunit -c phpunit.xml --testsuite=unit
          - php vendor/bin/phpunit -c phpunit.xml --testsuite=unit
        services:
          - elasticsearch
definitions:
  services:
    elasticsearch:
      image: smartdevs/elasticsearch:latest
      environment:
        "bootstrap.memory_lock": "true"
        "ES_JAVA_OPTS": "-Xms256m -Xmx256m"